def get_synonyms():
    return {
        # Compras - Compras
        'shopping': 'compras',
        'buying': 'compras',
        'purchase': 'compras',
        'shop': 'compras',
        'comprar': 'compras',
        'adquisición': 'compras',
        'compra': 'compras',
        'compras': 'compras',

        # Compras - Bebés, niños
        'baby': 'bebés, niños',
        'children': 'bebés, niños',
        'kids': 'bebés, niños',
        'infants': 'bebés, niños',
        'niños': 'bebés, niños',
        'bebé': 'bebés, niños',
        'pequeños': 'bebés, niños',
        'bebés, niños': 'bebés, niños',

        # Compras - Casa y jardín
        'home': 'casa y jardín',
        'garden': 'casa y jardín',
        'yard': 'casa y jardín',
        'house': 'casa y jardín',
        'home improvement': 'casa y jardín',
        'casa': 'casa y jardín',
        'jardín': 'casa y jardín',
        'mejoras del hogar': 'casa y jardín',
        'casa y jardín': 'casa y jardín',

        # Compras - Electrónica, accesorios
        'electronics': 'electrónica, accesorios',
        'gadgets': 'electrónica, accesorios',
        'devices': 'electrónica, accesorios',
        'tech': 'electrónica, accesorios',
        'accessories': 'electrónica, accesorios',
        'electrónica': 'electrónica, accesorios',
        'accesorios': 'electrónica, accesorios',
        'electrónica, accesorios': 'electrónica, accesorios',

        # Compras - Joyas, accesorios
        'jewelry': 'joyas, accesorios',
        'gems': 'joyas, accesorios',
        'accessories': 'joyas, accesorios',
        'jewels': 'joyas, accesorios',
        'joyería': 'joyas, accesorios',
        'joyas': 'joyas, accesorios',
        'accesorios': 'joyas, accesorios',
        'joyas, accesorios': 'joyas, accesorios',

        # Compras - Mascotas, animales
        'pets': 'mascotas, animales',
        'animals': 'mascotas, animales',
        'pet supplies': 'mascotas, animales',
        'pet care': 'mascotas, animales',
        'mascotas': 'mascotas, animales',
        'animales': 'mascotas, animales',
        'mascotas, animales': 'mascotas, animales',

        # Compras - Papelería, herramientas
        'stationery': 'papelería, herramientas',
        'office supplies': 'papelería, herramientas',
        'tools': 'papelería, herramientas',
        'writing supplies': 'papelería, herramientas',
        'papelería': 'papelería, herramientas',
        'herramientas': 'papelería, herramientas',
        'papelería, herramientas': 'papelería, herramientas',

        # Compras - Regalos
        'gifts': 'regalos',
        'presents': 'regalos',
        'souvenirs': 'regalos',
        'regalo': 'regalos',
        'presente': 'regalos',
        'obsequios': 'regalos',
        'regalos': 'regalos',

        # Compras - Ropa y calzado
        'clothing': 'ropa y calzado',
        'apparel': 'ropa y calzado',
        'shoes': 'ropa y calzado',
        'footwear': 'ropa y calzado',
        'clothes': 'ropa y calzado',
        'ropa': 'ropa y calzado',
        'calzado': 'ropa y calzado',
        'ropa y calzado': 'ropa y calzado',

        # Compras - Tiempo libre
        'leisure': 'tiempo libre',
        'free time': 'tiempo libre',
        'recreation': 'tiempo libre',
        'hobbies': 'tiempo libre',
        'tiempo libre': 'tiempo libre',
        'ocio': 'tiempo libre',
        'recreación': 'tiempo libre',
        'pasatiempos': 'tiempo libre',
        'tiempo libre': 'tiempo libre',

        # Compras - Libros
        'books': 'libros',
        'reading': 'libros',
        'novels': 'libros',
        'literature': 'libros',
        'libro': 'libros',
        'lectura': 'libros',
        'novela': 'libros',
        'literatura': 'libros',
        'libros': 'libros',

        # ---------------------------------------------------------

        # Alimentos y bebidas - Alimentos y bebidas
        'food': 'alimentos y bebidas',
        'meals': 'alimentos y bebidas',
        'drinks': 'alimentos y bebidas',
        'groceries': 'alimentos y bebidas',
        'comida': 'alimentos y bebidas',
        'bebidas': 'alimentos y bebidas',
        'alimentación': 'alimentos y bebidas',
        'alimentos y bebidas': 'alimentos y bebidas',

        # Alimentos y bebidas - Comestibles, despensa
        'groceries': 'comestibles, despensa',
        'pantry': 'comestibles, despensa',
        'supplies': 'comestibles, despensa',
        'grocery': 'comestibles, despensa',
        'comestibles': 'comestibles, despensa',
        'despensa': 'comestibles, despensa',
        'víveres': 'comestibles, despensa',
        'provisiones': 'comestibles, despensa',
        'abarrotes': 'comestibles, despensa',
        'comestibles, despensa': 'comestibles, despensa',

        # Alimentos y bebidas - Restaurante, comida rápida
        'restaurant': 'restaurante, comida rápida',
        'fast food': 'restaurante, comida rápida',
        'dining out': 'restaurante, comida rápida',
        'takeout': 'restaurante, comida rápida',
        'restaurante': 'restaurante, comida rápida',
        'comida rápida': 'restaurante, comida rápida',
        'comida para llevar': 'restaurante, comida rápida',
        'comida rápida': 'restaurante, comida rápida',
        'restaurante, comida rápida': 'restaurante, comida rápida',

        # Alimentos y bebidas - Café
        'coffee': 'café',
        'espresso': 'café',
        'latte': 'café',
        'mocha': 'café',
        'cappuccino': 'café',
        'cafetería': 'café',
        'café': 'café',

        # Alimentos y bebidas - Alcohol
        'alcohol': 'alcohol',
        'liquor': 'alcohol',
        'spirits': 'alcohol',
        'booze': 'alcohol',
        'drinks': 'alcohol',
        'bebidas alcohólicas': 'alcohol',
        'licor': 'alcohol',
        'bebidas': 'alcohol',

        # Alimentos y bebidas - Vino
        'wine': 'vino',
        'red wine': 'vino',
        'white wine': 'vino',
        'vino tinto': 'vino',
        'vino blanco': 'vino',
        'vino': 'vino',

        # ---------------------------------------------------------

        # Seguros - Seguros
        'insurance': 'seguros',
        'coverage': 'seguros',
        'policy': 'seguros',
        'insurance policy': 'seguros',
        'seguros': 'seguros',
        'póliza': 'seguros',
        'cobertura': 'seguros',

        # Seguros - Hogar
        'home insurance': 'hogar',
        'house insurance': 'hogar',
        'property insurance': 'hogar',
        'home coverage': 'hogar',
        'seguro de hogar': 'hogar',
        'seguro de vivienda': 'hogar',
        'seguro de propiedad': 'hogar',
        'hogar': 'hogar',

        # Seguros - Médico
        'medical insurance': 'médico',
        'health insurance': 'médico',
        'doctor coverage': 'médico',
        'healthcare insurance': 'médico',
        'seguro médico': 'médico',
        'seguro de salud': 'médico',
        'seguro de atención médica': 'médico',
        'médico': 'médico',

        # Seguros - Viaje
        'travel insurance': 'viaje',
        'trip insurance': 'viaje',
        'vacation insurance': 'viaje',
        'journey insurance': 'viaje',
        'seguro de viaje': 'viaje',
        'seguro de viajes': 'viaje',
        'seguro para viajeros': 'viaje',
        'viaje': 'viaje',

        # Seguros - Vida
        'life insurance': 'vida',
        'personal insurance': 'vida',
        'long-term insurance': 'vida',
        'life coverage': 'vida',
        'seguro de vida': 'vida',
        'seguro personal': 'vida',
        'cobertura de vida': 'vida',
        'vida': 'vida',

        # Seguros - Auto
        'car insurance': 'auto',
        'vehicle insurance': 'auto',
        'automobile insurance': 'auto',
        'auto insurance': 'auto',
        'seguro de auto': 'auto',
        'seguro de vehículo': 'auto',
        'seguro de automóvil': 'auto',
        'auto': 'auto',

        # Seguros - Motocicleta
        'motorcycle insurance': 'motocicleta',
        'bike insurance': 'motocicleta',
        'motorbike insurance': 'motocicleta',
        'seguro de motocicleta': 'motocicleta',
        'seguro de moto': 'motocicleta',
        'motocicleta': 'motocicleta',
        'moto': 'motocicleta',

        # Seguros - Mascota
        'pet insurance': 'mascota',
        'animal insurance': 'mascota',
        'dog insurance': 'mascota',
        'cat insurance': 'mascota',
        'seguro de mascota': 'mascota',
        'seguro de animales': 'mascota',
        'seguro de perros': 'mascota',
        'seguro de gatos': 'mascota',
        'mascota': 'mascota',

        # ---------------------------------------------------------

        # Vivienda - Vivienda
        'housing': 'vivienda',
        'home': 'vivienda',
        'residence': 'vivienda',
        'dwelling': 'vivienda',
        'living space': 'vivienda',
        'vivienda': 'vivienda',
        'hogar': 'vivienda',
        'casa': 'vivienda',

        # Vivienda - Renta
        'rent': 'renta',
        'leasing': 'renta',
        'lease': 'renta',
        'rental': 'renta',
        'renta': 'renta',
        'alquiler': 'renta',
        'arrendamiento': 'renta',

        # Vivienda - Mantenimiento, reparaciones
        'maintenance': 'mantenimiento, reparaciones',
        'repairs': 'mantenimiento, reparaciones',
        'upkeep': 'mantenimiento, reparaciones',
        'fixes': 'mantenimiento, reparaciones',
        'repair work': 'mantenimiento, reparaciones',
        'mantenimiento': 'mantenimiento, reparaciones',
        'reparaciones': 'mantenimiento, reparaciones',
        'arreglos': 'mantenimiento, reparaciones',
        'mantenimiento, reparaciones': 'mantenimiento, reparaciones',

        # Vivienda - Servicio doméstico
        'domestic service': 'servicio doméstico',
        'housekeeping': 'servicio doméstico',
        'house cleaning': 'servicio doméstico',
        'maid service': 'servicio doméstico',
        'cleaning service': 'servicio doméstico',
        'servicio doméstico': 'servicio doméstico',
        'servicio de limpieza': 'servicio doméstico',
        'limpieza': 'servicio doméstico',
        'empleada doméstica': 'servicio doméstico',

        # Vivienda - Alarmas y seguridad
        'alarms': 'alarmas y seguridad',
        'security': 'alarmas y seguridad',
        'home security': 'alarmas y seguridad',
        'security systems': 'alarmas y seguridad',
        'alarm systems': 'alarmas y seguridad',
        'alarmas': 'alarmas y seguridad',
        'seguridad': 'alarmas y seguridad',
        'sistemas de seguridad': 'alarmas y seguridad',
        'sistemas de alarmas': 'alarmas y seguridad',
        'alarmas y seguridad': 'alarmas y seguridad',

        # ---------------------------------------------------------

        # Vehículos - Vehículos
        'vehicles': 'vehículos',
        'car': 'vehículos',
        'vehicle': 'vehículos',
        'automobile': 'vehículos',
        'cars': 'vehículos',
        'vehículos': 'vehículos',
        'autos': 'vehículos',
        'coches': 'vehículos',
        'automóviles': 'vehículos',

        # Vehículos - Alquiler
        'rent': 'alquiler',
        'car rental': 'alquiler',
        'rental': 'alquiler',
        'leasing': 'alquiler',
        'lease': 'alquiler',
        'alquiler': 'alquiler',
        'arrendamiento': 'alquiler',
        'renta': 'alquiler',

        # Vehículos - Combustible
        'fuel': 'combustible',
        'gasoline': 'combustible',
        'diesel': 'combustible',
        'petrol': 'combustible',
        'gas': 'combustible',
        'combustible': 'combustible',
        'gasolina': 'combustible',
        'diésel': 'combustible',

        # Vehículos - Estacionamiento
        'parking': 'estacionamiento',
        'parking lot': 'estacionamiento',
        'parking fee': 'estacionamiento',
        'parking space': 'estacionamiento',
        'estacionamiento': 'estacionamiento',
        'aparcar': 'estacionamiento',
        'parqueadero': 'estacionamiento',
        'parking': 'estacionamiento',

        # Vehículos - Mantenimiento
        'maintenance': 'mantenimiento',
        'repairs': 'mantenimiento',
        'vehicle maintenance': 'mantenimiento',
        'upkeep': 'mantenimiento',
        'mantenimiento': 'mantenimiento',
        'reparaciones': 'mantenimiento',
        'cuidado del vehículo': 'mantenimiento',

        # Vehículos - Compra de vehículo
        'vehicle purchase': 'compra de vehículo',
        'car purchase': 'compra de vehículo',
        'buying a car': 'compra de vehículo',
        'buying a vehicle': 'compra de vehículo',
        'compra de vehículo': 'compra de vehículo',
        'compra de auto': 'compra de vehículo',
        'compra de coche': 'compra de vehículo',

        # ---------------------------------------------------------

        # Transporte - Transporte
        'transport': 'transporte',
        'vehicles': 'transporte',
        'cars': 'transporte',
        'bikes': 'transporte',
        'trucks': 'transporte',
        'automobiles': 'transporte',
        'motos': 'transporte',
        'vehículos': 'transporte',
        'transporte': 'transporte',
        'transporte, vehículos': 'transporte',

        # Transporte - Larga distancia
        'long distance transport': 'larga distancia',
        'intercity': 'larga distancia',
        'highway travel': 'larga distancia',
        'road trip': 'larga distancia',
        'viaje largo': 'larga distancia',
        'transporte interurbano': 'larga distancia',
        'transporte largo': 'larga distancia',
        'larga distancia': 'larga distancia',
        'viajes largos': 'larga distancia',
        'autobús de larga distancia': 'larga distancia',

        # Transporte - Taxi
        'taxi': 'taxi',
        'cab': 'taxi',
        'ride-hailing': 'taxi',
        'uber': 'taxi',
        'lyft': 'taxi',
        'auto de alquiler': 'taxi',
        'vehículo privado': 'taxi',
        'taxista': 'taxi',
        'transporte privado': 'taxi',
        'transporte en taxi': 'taxi',

        # Transporte - Transporte público
        'public transport': 'transporte público',
        'bus': 'transporte público',
        'metro': 'transporte público',
        'train': 'transporte público',
        'subway': 'transporte público',
        'trolebús': 'transporte público',
        'autobús público': 'transporte público',
        'transporte colectivo': 'transporte público',
        'transporte masivo': 'transporte público',
        'transporte urbano': 'transporte público',
        'transporte público': 'transporte público',

        # Transporte - Viajes de negocio
        'business trip': 'viajes de negocio',
        'corporate travel': 'viajes de negocio',
        'work trip': 'viajes de negocio',
        'business travel': 'viajes de negocio',
        'viaje de trabajo': 'viajes de negocio',
        'viaje corporativo': 'viajes de negocio',
        'viaje de negocios': 'viajes de negocio',
        'traslado corporativo': 'viajes de negocio',
        'viaje profesional': 'viajes de negocio',
        'viajes de negocio': 'viajes de negocio',

        # Transporte - Estacionamiento y casetas
        'parking': 'estacionamiento y casetas',
        'parking lot': 'estacionamiento y casetas',
        'parqueadero': 'estacionamiento y casetas',
        'garaje': 'estacionamiento y casetas',
        'casetas de peaje': 'estacionamiento y casetas',
        'peaje': 'estacionamiento y casetas',
        'estacionamiento': 'estacionamiento y casetas',
        'área de estacionamiento': 'estacionamiento y casetas',
        'peaje de carretera': 'estacionamiento y casetas',
        'parqueo': 'estacionamiento y casetas',
        'estacionamiento y casetas': 'estacionamiento y casetas',

        # ---------------------------------------------------------

        # Vida y entretenimiento - Vida y entretenimiento
        'life and entertainment': 'vida y entretenimiento',
        'entertainment': 'vida y entretenimiento',
        'life': 'vida y entretenimiento',
        'fun': 'vida y entretenimiento',
        'vida y entretenimiento': 'vida y entretenimiento',
        'diversión': 'vida y entretenimiento',

        # Vida y entretenimiento - Educación, desarrollo
        'education': 'educación, desarrollo',
        'development': 'educación, desarrollo',
        'learning': 'educación, desarrollo',
        'training': 'educación, desarrollo',
        'educación': 'educación, desarrollo',
        'desarrollo': 'educación, desarrollo',
        'formación': 'educación, desarrollo',
        'aprendizaje': 'educación, desarrollo',
        'educación, desarrollo': 'educación, desarrollo',

        # Vida y entretenimiento - Pasatiempos
        'hobbies': 'pasatiempos',
        'pastimes': 'pasatiempos',
        'movies': 'pasatiempos',
        'leisure activities': 'pasatiempos',
        'pasatiempos': 'pasatiempos',
        'aficiones': 'pasatiempos',
        'hobbies': 'pasatiempos',
        'películas': 'pasatiempos',


        # Vida y entretenimiento - Vacaciones, viajes, hoteles
        'vacation': 'vacaciones, viajes, hoteles',
        'travel': 'vacaciones, viajes, hoteles',
        'hotels': 'vacaciones, viajes, hoteles',
        'trip': 'vacaciones, viajes, hoteles',
        'holidays': 'vacaciones, viajes, hoteles',
        'vacaciones': 'vacaciones, viajes, hoteles',
        'viajes': 'vacaciones, viajes, hoteles',
        'hoteles': 'vacaciones, viajes, hoteles',
        'turismo': 'vacaciones, viajes, hoteles',
        'vacaciones, viajes, hoteles': 'vacaciones, viajes, hoteles',

        # Vida y entretenimiento - Apuestas
        'gambling': 'apuestas',
        'betting': 'apuestas',
        'wagering': 'apuestas',
        'casino': 'apuestas',
        'juego': 'apuestas',
        'apuestas': 'apuestas',

        # Vida y entretenimiento - Diversión y celebraciones
        'fun': 'diversión y celebraciones',
        'celebrations': 'diversión y celebraciones',
        'parties': 'diversión y celebraciones',
        'festivities': 'diversión y celebraciones',
        'fiestas': 'diversión y celebraciones',
        'diversiones': 'diversión y celebraciones',
        'celebraciones': 'diversión y celebraciones',
        'diversión y celebraciones': 'diversión y celebraciones',

        # Vida y entretenimiento - Cigarros, tabaco
        'cigarettes': 'cigarros, tabaco',
        'tobacco': 'cigarros, tabaco',
        'smoking': 'cigarros, tabaco',
        'cigars': 'cigarros, tabaco',
        'cigarros': 'cigarros, tabaco',
        'tabaco': 'cigarros, tabaco',
        'fumar': 'cigarros, tabaco',
        'cigarros, tabaco': 'cigarros, tabaco',

        # Vida y entretenimiento - Bienestar, belleza
        'well-being': 'bienestar, belleza',
        'beauty': 'bienestar, belleza',
        'health': 'bienestar, belleza',
        'skincare': 'bienestar, belleza',
        'wellness': 'bienestar, belleza',
        'bienestar': 'bienestar, belleza',
        'belleza': 'bienestar, belleza',
        'salud': 'bienestar, belleza',
        'cuidado de la piel': 'bienestar, belleza',
        'bienestar, belleza': 'bienestar, belleza',

        # Vida y entretenimiento - Caridad, regalos
        'charity': 'caridad, regalos',
        'gifts': 'caridad, regalos',
        'donations': 'caridad, regalos',
        'giving': 'caridad, regalos',
        'caridad': 'caridad, regalos',
        'regalos': 'caridad, regalos',
        'donaciones': 'caridad, regalos',
        'caridad, regalos': 'caridad, regalos',

        # Vida y entretenimiento - Cultura, arte, eventos deportivos
        'culture': 'cultura, arte, eventos deportivos',
        'art': 'cultura, arte, eventos deportivos',
        'sports events': 'cultura, arte, eventos deportivos',
        'concerts': 'cultura, arte, eventos deportivos',
        'exhibitions': 'cultura, arte, eventos deportivos',
        'cultura': 'cultura, arte, eventos deportivos',
        'arte': 'cultura, arte, eventos deportivos',
        'eventos deportivos': 'cultura, arte, eventos deportivos',
        'espectáculos': 'cultura, arte, eventos deportivos',
        'cultura, arte, eventos deportivos': 'cultura, arte, eventos deportivos',

        # ---------------------------------------------------------
        # Salud y deporte - Salud y deporte
        'fitness': 'salud y deporte',
        'gym': 'salud y deporte',
        'yoga': 'salud y deporte',
        'exercise': 'salud y deporte',
        'nutrition': 'salud y deporte',
        'wellness': 'salud y deporte',
        'rehabilitation': 'salud y deporte',
        'physical therapy': 'salud y deporte',
        'mental health': 'salud y deporte',
        'sports': 'salud y deporte',
        'athletics': 'salud y deporte',
        'running': 'salud y deporte',
        'strength training': 'salud y deporte',
        'cardio': 'salud y deporte',
        'meditation': 'salud y deporte',
        'crossfit': 'salud y deporte',
        'salud y deporte': 'salud y deporte',

        # Salud y deporte - Deporte, gym
        'weightlifting': 'deporte, gym',
        'levantamiento de pesas': 'deporte, gym',
        'bodybuilding': 'deporte, gym',
        'culturismo': 'deporte, gym',
        'crossfit': 'deporte, gym',
        'cardio': 'deporte, gym',
        'cinta de correr': 'deporte, gym',
        'treadmill': 'deporte, gym',
        'workout': 'deporte, gym',
        'entrenamiento': 'deporte, gym',
        'squats': 'deporte, gym',
        'sentadillas': 'deporte, gym',
        'bench press': 'deporte, gym',
        'press de banca': 'deporte, gym',
        'personal trainer': 'deporte, gym',
        'entrenador personal': 'deporte, gym',
        'strength training': 'deporte, gym',
        'entrenamiento de fuerza': 'deporte, gym',
        'cycling': 'deporte, gym',
        'ciclismo': 'deporte, gym',
        'elliptical': 'deporte, gym',
        'elíptica': 'deporte, gym',
        'HIIT': 'deporte, gym',
        'entrenamiento HIIT': 'deporte, gym',
        'dumbbells': 'deporte, gym',
        'mancuernas': 'deporte, gym',
        'barbell': 'deporte, gym',
        'barra de pesas': 'deporte, gym',
        'calisthenics': 'deporte, gym',
        'calistenia': 'deporte, gym',
        'gym membership': 'deporte, gym',
        'membresía de gimnasio': 'deporte, gym',
        'deporte, gym': 'deporte, gym',

        # Salud y deporte - Medico
        'doctor': 'medico',
        'médico': 'medico',
        'consultation': 'medico',
        'consulta': 'medico',
        'hospital': 'medico',
        'clínica': 'medico',
        'clinica': 'medico',
        'specialist': 'medico',
        'especialista': 'medico',
        'check-up': 'medico',
        'revisión': 'medico',
        'appointment': 'medico',
        'cita médica': 'medico',
        'health check': 'medico',
        'chequeo médico': 'medico',
        'general practice': 'medico',
        'medicina general': 'medico',
        'pediatrics': 'medico',
        'pediatría': 'medico',
        'cardiology': 'medico',
        'cardiología': 'medico',
        'dermatology': 'medico',
        'dermatología': 'medico',
        'gynecology': 'medico',
        'ginecología': 'medico',
        'medico': 'medico',

        # Salud y deporte - Farmacia
        'pharmacy': 'farmacia',
        'farmacia': 'farmacia',
        'medicine': 'farmacia',
        'medicamento': 'farmacia',
        'prescription': 'farmacia',
        'receta médica': 'farmacia',
        'vitamins': 'farmacia',
        'vitaminas': 'farmacia',
        'over-the-counter': 'farmacia',
        'sin receta': 'farmacia',
        'pain reliever': 'farmacia',
        'analgésico': 'farmacia',
        'antibiotics': 'farmacia',
        'antibióticos': 'farmacia',
        'first aid': 'farmacia',
        'primeros auxilios': 'farmacia',
        'health supplements': 'farmacia',
        'suplementos de salud': 'farmacia',

        # Salud y deporte - Optica
        'optician': 'optica',
        'óptico': 'optica',
        'glasses': 'optica',
        'gafas': 'optica',
        'contact lenses': 'optica',
        'lentes de contacto': 'optica',
        'eye test': 'optica',
        'examen de la vista': 'optica',
        'vision care': 'optica',
        'cuidado de la vista': 'optica',
        'frames': 'optica',
        'monturas': 'optica',
        'prescription glasses': 'optica',
        'gafas graduadas': 'optica',
        'eye doctor': 'optica',
        'oftalmólogo': 'optica',
        'optometrist': 'optica',
        'optometrista': 'optica',
        'optica': 'optica',

        # Salud y deporte - Dentista
        'dentist': 'dentista',
        'dentista': 'dentista',
        'dental cleaning': 'dentista',
        'limpieza dental': 'dentista',
        'dental check-up': 'dentista',
        'revisión dental': 'dentista',
        'orthodontics': 'dentista',
        'ortodoncia': 'dentista',
        'fillings': 'dentista',
        'empastes': 'dentista',
        'tooth extraction': 'dentista',
        'extracción dental': 'dentista',
        'braces': 'dentista',
        'frenos': 'dentista',
        'teeth whitening': 'dentista',
        'blanqueamiento dental': 'dentista',
        'root canal': 'dentista',
        'tratamiento de conducto': 'dentista',

        # ---------------------------------------------------------
        # Suscripciones y servicios - Suscripciones y servicios
        'subscription': 'suscripciones y servicios',
        'suscripción': 'suscripciones y servicios',
        'service': 'suscripciones y servicios',
        'servicio': 'suscripciones y servicios',
        'monthly fee': 'suscripciones y servicios',
        'tarifa mensual': 'suscripciones y servicios',
        'renewal': 'suscripciones y servicios',
        'renovación': 'suscripciones y servicios',
        'suscripciones y servicios': 'suscripciones y servicios',

        # Suscripciones y servicios - Compras y servicios online
        'online shopping': 'compras y servicios online',
        'compras en línea': 'compras y servicios online',
        'e-commerce': 'compras y servicios online',
        'comercio electrónico': 'compras y servicios online',
        'delivery': 'compras y servicios online',
        'envío a domicilio': 'compras y servicios online',
        'online service': 'compras y servicios online',
        'servicio en línea': 'compras y servicios online',
        'home delivery': 'compras y servicios online',
        'entrega a domicilio': 'compras y servicios online',
        'online': 'compras y servicios online',
        'compras y servicios online': 'compras y servicios online',

        # Suscripciones y servicios - Celular
        'cellphone': 'celular',
        'teléfono celular': 'celular',
        'mobile plan': 'celular',
        'plan móvil': 'celular',
        'data plan': 'celular',
        'plan de datos': 'celular',
        'prepaid': 'celular',
        'prepago': 'celular',
        'postpaid': 'celular',
        'pospago': 'celular',
        'recharge': 'celular',
        'recarga': 'celular',
        'celular': 'celular',

        # Suscripciones y servicios - Entretenimiento digital
        'streaming': 'entretenimiento digital',
        'transmisión': 'entretenimiento digital',
        'music streaming': 'entretenimiento digital',
        'transmisión de música': 'entretenimiento digital',
        'video streaming': 'entretenimiento digital',
        'transmisión de video': 'entretenimiento digital',
        'movie rental': 'entretenimiento digital',
        'alquiler de películas': 'entretenimiento digital',
        'audiobook': 'entretenimiento digital',
        'libro de audio': 'entretenimiento digital',
        'podcasts': 'entretenimiento digital',
        'entretenimiento digital': 'entretenimiento digital',

        # Suscripciones y servicios - Internet, televisión, telefonía
        'internet': 'internet, televisión, telefonía',
        'wifi': 'internet, televisión, telefonía',
        'broadband': 'internet, televisión, telefonía',
        'banda ancha': 'internet, televisión, telefonía',
        'cable TV': 'internet, televisión, telefonía',
        'televisión por cable': 'internet, televisión, telefonía',
        'satellite TV': 'internet, televisión, telefonía',
        'televisión satelital': 'internet, televisión, telefonía',
        'landline': 'internet, televisión, telefonía',
        'línea fija': 'internet, televisión, telefonía',
        'tv': 'internet, televisión, telefonía',
        'internet, televisión, telefonía': 'internet, televisión, telefonía',

        # Suscripciones y servicios - Software, aplicaciones, juegos
        'software': 'software, aplicaciones, juegos',
        'aplicaciones': 'software, aplicaciones, juegos',
        'apps': 'software, aplicaciones, juegos',
        'video games': 'software, aplicaciones, juegos',
        'videojuegos': 'software, aplicaciones, juegos',
        'PC games': 'software, aplicaciones, juegos',
        'juegos para PC': 'software, aplicaciones, juegos',
        'app subscription': 'software, aplicaciones, juegos',
        'suscripción a aplicaciones': 'software, aplicaciones, juegos',
        'app': 'software, aplicaciones, juegos',
        'software, aplicaciones, juegos': 'software, aplicaciones, juegos',

        # Suscripciones y servicios - Electricidad
        'electricity': 'electricidad',
        'electricidad': 'electricidad',
        'power bill': 'electricidad',
        'factura de luz': 'electricidad',
        'utility bill': 'electricidad',
        'servicio de luz': 'electricidad',
        'energy consumption': 'electricidad',
        'consumo de energía': 'electricidad',
        'luz': 'electricidad',

        # Suscripciones y servicios - Agua
        'water': 'agua',
        'agua': 'agua',
        'water bill': 'agua',
        'factura de agua': 'agua',
        'water service': 'agua',
        'servicio de agua': 'agua',
        'utility bill': 'agua',
        'servicios de agua': 'agua',

        # Suscripciones y servicios - Gas
        'gas': 'gas',
        'gas natural': 'gas',
        'gas bill': 'gas',
        'factura de gas': 'gas',
        'natural gas service': 'gas',
        'servicio de gas': 'gas',
        'gas connection': 'gas',
        'conexión de gas': 'gas',

        # ---------------------------------------------------------
        # Gastos financieros - Gastos financieros
        'financial expenses': 'gastos financieros',
        'gastos financieros': 'gastos financieros',
        'bank fees': 'gastos financieros',
        'comisiones bancarias': 'gastos financieros',
        'interest': 'gastos financieros',
        'intereses': 'gastos financieros',
        'financial charges': 'gastos financieros',
        'cargos financieros': 'gastos financieros',

        # Gastos financieros - Asignación familiar
        'family allowance': 'asignación familiar',
        'asignación familiar': 'asignación familiar',
        'child support': 'asignación familiar',
        'apoyo familiar': 'asignación familiar',
        'dependents': 'asignación familiar',
        'dependientes': 'asignación familiar',
        'familia': 'asignación familiar',

        # Gastos financieros - Cargos, honorarios
        'fees': 'cargos, honorarios',
        'honorarios': 'cargos, honorarios',
        'consulting fee': 'cargos, honorarios',
        'cargo de consultoría': 'cargos, honorarios',
        'consultoría': 'cargos, honorarios',
        'service charge': 'cargos, honorarios',
        'cargo por servicio': 'cargos, honorarios',
        'commission': 'cargos, honorarios',
        'comisión': 'cargos, honorarios',
        'cargos, honorarios': 'cargos, honorarios',

        # Gastos financieros - Asesores, abogados
        'advisor': 'asesores, abogados',
        'asesor': 'asesores, abogados',
        'lawyer': 'asesores, abogados',
        'abogado': 'asesores, abogados',
        'legal services': 'asesores, abogados',
        'servicios legales': 'asesores, abogados',
        'consultant': 'asesores, abogados',
        'consultor': 'asesores, abogados',
        'asesores, abogados': 'asesores, abogados',

        # Gastos financieros - Impuestos
        'tax': 'impuestos',
        'impuesto': 'impuestos',
        'income tax': 'impuestos',
        'impuesto sobre la renta': 'impuestos',
        'isr': 'impuestos',
        'sales tax': 'impuestos',
        'impuesto sobre ventas': 'impuestos',
        'property tax': 'impuestos',
        'impuesto predial': 'impuestos',
        'predial': 'impuestos',
        'tax return': 'impuestos',
        'declaración de impuestos': 'impuestos',
        'impuestos': 'impuestos',

        # Gastos financieros - Multas, licencias
        'fines': 'multas, licencias',
        'multas': 'multas, licencias',
        'licenses': 'multas, licencias',
        'licencias': 'multas, licencias',
        'traffic fine': 'multas, licencias',
        'multa de tráfico': 'multas, licencias',
        'renewal fee': 'multas, licencias',
        'cargo de renovación': 'multas, licencias',
        'penalty': 'multas, licencias',
        'multas, licencias': 'multas, licencias',

        # Gastos financieros - Tramites y registro civil
        'civil registry': 'tramites y registro civil',
        'registro civil': 'tramites y registro civil',
        'official paperwork': 'tramites y registro civil',
        'trámites oficiales': 'tramites y registro civil',
        'birth certificate': 'tramites y registro civil',
        'certificado de nacimiento': 'tramites y registro civil',
        'marriage license': 'tramites y registro civil',
        'licencia de matrimonio': 'tramites y registro civil',
        'tramites y registro civil': 'tramites y registro civil',

        # Gastos financieros - Préstamos
        'loan': 'préstamos',
        'préstamo': 'préstamos',
        'mortgage': 'préstamos',
        'hipoteca': 'préstamos',
        'personal loan': 'préstamos',
        'préstamo personal': 'préstamos',
        'credit line': 'préstamos',
        'línea de crédito': 'préstamos',
        'crédito': 'préstamos',
        'préstamos': 'préstamos',

        # Gastos financieros - Pensión familiar
        'family pension': 'pensión familiar',
        'pensión familiar': 'pensión familiar',
        'retirement fund': 'pensión familiar',
        'fondo de jubilación': 'pensión familiar',
        'benefits': 'pensión familiar',
        'beneficios': 'pensión familiar', # ???????????????????????????
        'dependents pension': 'pensión familiar',
        'pensión de dependientes': 'pensión familiar',

        # Gastos financieros - Seguro social, salud
        'social security': 'seguro social, salud',
        'seguro social': 'seguro social, salud',
        'health insurance': 'seguro social, salud',
        'seguro de salud': 'seguro social, salud',
        'healthcare': 'seguro social, salud',
        'cuidado de la salud': 'seguro social, salud',
        'medical insurance': 'seguro social, salud',
        'seguro médico': 'seguro social, salud',
        'seguro social, salud': 'seguro social, salud',

        # ---------------------------------------------------------
        # Inversiones - Inversiones
        'investment': 'inversiones',
        'inversión': 'inversiones',
        'capital': 'inversiones',
        'portfolio': 'inversiones',
        'portafolio': 'inversiones',
        'assets': 'inversiones',
        'activos': 'inversiones',
        'financial growth': 'inversiones',
        'crecimiento financiero': 'inversiones',
        'inversiones': 'inversiones',

        # Inversiones - Coleccionables
        'collectibles': 'coleccionables',
        'coleccionables': 'coleccionables',
        'antiques': 'coleccionables',
        'antigüedades': 'coleccionables',
        'artwork': 'coleccionables',
        'obras de arte': 'coleccionables',
        'stamps': 'coleccionables',
        'sellos': 'coleccionables',
        'rare coins': 'coleccionables',
        'monedas raras': 'coleccionables',
        'memorabilia': 'coleccionables',
        'recuerdos': 'coleccionables',

        # Inversiones - Ahorros
        'savings': 'ahorros',
        'ahorros': 'ahorros',
        'savings account': 'ahorros',
        'cuenta de ahorros': 'ahorros',
        'emergency fund': 'ahorros',
        'fondo de emergencia': 'ahorros',
        'savings plan': 'ahorros',
        'plan de ahorros': 'ahorros',
        'personal savings': 'ahorros',
        'ahorros personales': 'ahorros',

        # Inversiones - Inversiones financieras
        'financial investment': 'inversiones financieras',
        'inversiones financieras': 'inversiones financieras',
        'stocks': 'inversiones financieras',
        'acciones': 'inversiones financieras',
        'bonds': 'inversiones financieras',
        'bonos': 'inversiones financieras',
        'mutual funds': 'inversiones financieras',
        'fondos mutuos': 'inversiones financieras',
        'ETFs': 'inversiones financieras',
        'fondos cotizados': 'inversiones financieras',
        'retirement fund': 'inversiones financieras',
        'fondo de jubilación': 'inversiones financieras',

        # Inversiones - Bienes raíces
        'real estate': 'bienes raíces',
        'bienes raíces': 'bienes raíces',
        'property investment': 'bienes raíces',
        'inversión en propiedades': 'bienes raíces',
        'housing market': 'bienes raíces',
        'mercado inmobiliario': 'bienes raíces',
        'land': 'bienes raíces',
        'terreno': 'bienes raíces',
        'real estate portfolio': 'bienes raíces',
        'portafolio inmobiliario': 'bienes raíces',
        'fibras': 'bienes raíces',

        # Inversiones - Vehículos, propiedades
        'vehicles': 'vehículos, propiedades',
        'vehículos': 'vehículos, propiedades',
        'property': 'vehículos, propiedades',
        'propiedad': 'vehículos, propiedades',
        'car investment': 'vehículos, propiedades',
        'inversión en automóviles': 'vehículos, propiedades',
        'real estate properties': 'vehículos, propiedades',
        'propiedades inmobiliarias': 'vehículos, propiedades',
        'luxury cars': 'vehículos, propiedades',
        'automóviles de lujo': 'vehículos, propiedades',
        'investment property': 'vehículos, propiedades',
        'propiedad de inversión': 'vehículos, propiedades',
        'vehículos, propiedades': 'vehículos, propiedades',

        # ---------------------------------------------------------
        # Ingresos - Ingresos
        'income': 'ingresos',
        'ingresos': 'ingresos',
        'earnings': 'ingresos',
        'ganancias': 'ingresos',
        'revenue': 'ingresos',
        'ingresos financieros': 'ingresos',

        # Ingresos - Salarios
        'salary': 'salarios',
        'salario': 'salarios',
        'wages': 'salarios',
        'sueldos': 'salarios',
        'paycheck': 'salarios',
        'nómina': 'salarios',
        'monthly income': 'salarios',
        'ingreso mensual': 'salarios',
        'hourly wage': 'salarios',
        'salario por hora': 'salarios',
        'salarios': 'salarios',

        # Ingresos - Rembolsos
        'reimbursement': 'reembolsos',
        'reembolso': 'reembolsos',
        'refund': 'reembolsos',
        'devolución': 'reembolsos',
        'expense claim': 'reembolsos',
        'reclamación de gastos': 'reembolsos',
        'reembolsos': 'reembolsos',

        # Ingresos - Lotería, juegos de azar
        'lottery': 'lotería, juegos de azar',
        'lotería': 'lotería, juegos de azar',
        'gambling': 'lotería, juegos de azar',
        'juegos de azar': 'lotería, juegos de azar',
        'casino winnings': 'lotería, juegos de azar',
        'casino': 'lotería, juegos de azar',
        'ganancias de casino': 'lotería, juegos de azar',
        'casino': 'lotería, juegos de azar',
        'lotería, juegos de azar': 'lotería, juegos de azar',

        # Ingresos - Rendimientos, inversiones
        'returns': 'rendimientos, inversiones',
        'rendimientos': 'rendimientos, inversiones',
        'investment income': 'rendimientos, inversiones',
        'ingresos por inversiones': 'rendimientos, inversiones',
        'dividends': 'rendimientos, inversiones',
        'dividendos': 'rendimientos, inversiones',
        'capital gains': 'rendimientos, inversiones',
        'ganancias de capital': 'rendimientos, inversiones',
        'interest income': 'rendimientos, inversiones',
        'ingresos por intereses': 'rendimientos, inversiones',

        # Ingresos - Regalos
        'gift': 'regalos',
        'regalo': 'regalos',
        'cash gift': 'regalos',
        'regalo en efectivo': 'regalos',
        'present': 'regalos',
        'obsequio': 'regalos',
        'family gift': 'regalos',
        'regalo familiar': 'regalos',
        'regalos': 'regalos',

        # Ingresos - Préstamos
        'loan': 'préstamos',
        'préstamo': 'préstamos',
        'borrowed money': 'préstamos',
        'dinero prestado': 'préstamos',
        'lending': 'préstamos',
        'préstamo recibido': 'préstamos',
        'préstamos': 'préstamos',

        # Ingresos - Pensiones
        'pension': 'pensiones',
        'pensión': 'pensiones',
        'retirement income': 'pensiones',
        'ingreso de jubilación': 'pensiones',
        'retirement funds': 'pensiones',
        'fondos de jubilación': 'pensiones',
        'pensiones': 'pensiones',

        # Ingresos - Ventas
        'sales': 'ventas',
        'ventas': 'ventas',
        'product sales': 'ventas',
        'ventas de productos': 'ventas',
        'item sales': 'ventas',
        'ventas de artículos': 'ventas',

        # Ingresos - Devolución impuestos
        'tax refund': 'devolución impuestos',
        'devolución de impuestos': 'devolución impuestos',
        'reembolso de impuestos': 'devolución impuestos',
        'impuestos': 'devolución impuestos',
        'tax return': 'devolución impuestos',
        'reembolso fiscal': 'devolución impuestos',
        'devolución impuestos': 'devolución impuestos',

        # Ingresos - Rentas
        'rental income': 'rentas',
        'ingresos por alquiler': 'rentas',
        'rent': 'rentas',
        'alquiler': 'rentas',
        'leasing': 'rentas',
        'arrendamiento': 'rentas',
        'renta': 'rentas',
        'rentas': 'rentas',

        # Ingresos - Subvenciones y ayudas
        'grant': 'subvenciones y ayudas',
        'subvención': 'subvenciones y ayudas',
        'aid': 'subvenciones y ayudas',
        'ayuda': 'subvenciones y ayudas',
        'financial support': 'subvenciones y ayudas',
        'apoyo financiero': 'subvenciones y ayudas',
        'government aid': 'subvenciones y ayudas',
        'ayuda gubernamental': 'subvenciones y ayudas',
        'subvenciones y ayudas': 'subvenciones y ayudas',
}
