"""Add created_at and updated_at to User model

Revision ID: 0be6c139413c
Revises: 60ad6f7febfb
Create Date: 2024-09-09 04:07:02.205383

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "0be6c139413c"
down_revision = "60ad6f7febfb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
    )
    op.add_column(
        "user", sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.execute('UPDATE "user" SET created_at = NOW() WHERE created_at IS NULL')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "updated_at")
    op.drop_column("user", "created_at")
    # ### end Alembic commands ###
