"""fix add account_id to expense

Revision ID: 0e747f730710
Revises: 1ebe11ed4e0a
Create Date: 2023-09-01 17:24:31.955256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e747f730710'
down_revision = '1ebe11ed4e0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expense', sa.Column('account_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'expense', 'account', ['account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'expense', type_='foreignkey')
    op.drop_column('expense', 'account_id')
    # ### end Alembic commands ###
