"""remove title from expense and add category relationship

Revision ID: 14cb7994c598
Revises: 8844eb40d730
Create Date: 2023-09-09 02:17:40.672111

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14cb7994c598'
down_revision = '8844eb40d730'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expense', sa.Column('category_id', sa.Integer(), nullable=True))
    op.drop_index('ix_expense_title', table_name='expense')
    op.create_foreign_key(None, 'expense', 'category', ['category_id'], ['id'])
    op.drop_column('expense', 'title')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expense', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'expense', type_='foreignkey')
    op.create_index('ix_expense_title', 'expense', ['title'], unique=False)
    op.drop_column('expense', 'category_id')
    # ### end Alembic commands ###
