"""adjust balance table

Revision ID: 1b088076d25c
Revises: 2ea7846f0c99
Create Date: 2025-10-11 20:35:50.289280

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1b088076d25c'
down_revision = '2ea7846f0c99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('balanceadjustment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('old_balance', sa.Float(), nullable=False),
    sa.Column('new_balance', sa.Float(), nullable=False),
    sa.Column('adjustment_amount', sa.Float(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('adjustment_date', sa.Date(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_balanceadjustment_account_id'), 'balanceadjustment', ['account_id'], unique=False)
    op.create_index(op.f('ix_balanceadjustment_adjustment_date'), 'balanceadjustment', ['adjustment_date'], unique=False)
    op.create_index(op.f('ix_balanceadjustment_id'), 'balanceadjustment', ['id'], unique=True)
    op.create_index(op.f('ix_balanceadjustment_owner_id'), 'balanceadjustment', ['owner_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_balanceadjustment_owner_id'), table_name='balanceadjustment')
    op.drop_index(op.f('ix_balanceadjustment_id'), table_name='balanceadjustment')
    op.drop_index(op.f('ix_balanceadjustment_adjustment_date'), table_name='balanceadjustment')
    op.drop_index(op.f('ix_balanceadjustment_account_id'), table_name='balanceadjustment')
    op.drop_table('balanceadjustment')
    # ### end Alembic commands ###
