"""Add date automatically to import

Revision ID: 1bf44fed8e19
Revises: edbcf36d408a
Create Date: 2024-10-23 22:29:56.638306

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bf44fed8e19'
down_revision = 'edbcf36d408a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('import', 'date',
               existing_type=sa.DATE(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True)
    op.drop_index('ix_import_date', table_name='import')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_import_date', 'import', ['date'], unique=False)
    op.alter_column('import', 'date',
               existing_type=sa.DateTime(timezone=True),
               type_=sa.DATE(),
               existing_nullable=True)
    # ### end Alembic commands ###
