"""add category and subcategory tables

Revision ID: 210562bb3adc
Revises: 39b6ea580369
Create Date: 2023-09-03 01:52:31.229455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '210562bb3adc'
down_revision = '39b6ea580369'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_color'), 'category', ['color'], unique=False)
    op.create_index(op.f('ix_category_description'), 'category', ['description'], unique=False)
    op.create_index(op.f('ix_category_icon'), 'category', ['icon'], unique=False)
    op.create_index(op.f('ix_category_id'), 'category', ['id'], unique=False)
    op.create_index(op.f('ix_category_name'), 'category', ['name'], unique=False)
    op.create_table('subcategory',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('color', sa.String(), nullable=False),
    sa.Column('icon', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subcategory_color'), 'subcategory', ['color'], unique=False)
    op.create_index(op.f('ix_subcategory_description'), 'subcategory', ['description'], unique=False)
    op.create_index(op.f('ix_subcategory_icon'), 'subcategory', ['icon'], unique=False)
    op.create_index(op.f('ix_subcategory_id'), 'subcategory', ['id'], unique=False)
    op.create_index(op.f('ix_subcategory_name'), 'subcategory', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subcategory_name'), table_name='subcategory')
    op.drop_index(op.f('ix_subcategory_id'), table_name='subcategory')
    op.drop_index(op.f('ix_subcategory_icon'), table_name='subcategory')
    op.drop_index(op.f('ix_subcategory_description'), table_name='subcategory')
    op.drop_index(op.f('ix_subcategory_color'), table_name='subcategory')
    op.drop_table('subcategory')
    op.drop_index(op.f('ix_category_name'), table_name='category')
    op.drop_index(op.f('ix_category_id'), table_name='category')
    op.drop_index(op.f('ix_category_icon'), table_name='category')
    op.drop_index(op.f('ix_category_description'), table_name='category')
    op.drop_index(op.f('ix_category_color'), table_name='category')
    op.drop_table('category')
    # ### end Alembic commands ###
