"""remove goal_id from income table

Revision ID: 26509aaa0bab
Revises: w8c5h14uldi0
Create Date: 2025-09-06 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26509aaa0bab'
down_revision = 'w8c5h14uldi0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'income', type_='foreignkey')
    op.drop_column('income', 'goal_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('income', sa.Column('goal_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'income', 'goal', ['goal_id'], ['id'])
    # ### end Alembic commands ###