"""default wa account

Revision ID: 2ea7846f0c99
Revises: a740c6e08748
Create Date: 2025-09-27 23:50:35.301919

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2ea7846f0c99'
down_revision = 'a740c6e08748'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('default_account_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'account', ['default_account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'default_account_id')
    # ### end Alembic commands ###
