"""add account model

Revision ID: 37e5650bd60b
Revises: 71779bc66bff
Create Date: 2023-09-01 17:13:31.983281

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "37e5650bd60b"
down_revision = "71779bc66bff"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "account",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("initial_balance", sa.Float(), nullable=True),
        sa.Column("current_balance", sa.Float(), nullable=True),
        sa.Column("total_expenses", sa.Float(), nullable=True),
        sa.Column("total_incomes", sa.Float(), nullable=True),
        sa.Column("total_transfers", sa.Float(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_account_current_balance"), "account", ["current_balance"], unique=False
    )
    op.create_index(op.f("ix_account_id"), "account", ["id"], unique=True)
    op.create_index(
        op.f("ix_account_initial_balance"), "account", ["initial_balance"], unique=False
    )
    op.create_index(op.f("ix_account_name"), "account", ["name"], unique=False)
    op.create_index(
        op.f("ix_account_total_expenses"), "account", ["total_expenses"], unique=False
    )
    op.create_index(
        op.f("ix_account_total_incomes"), "account", ["total_incomes"], unique=False
    )
    op.create_index(
        op.f("ix_account_total_transfers"), "account", ["total_transfers"], unique=False
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_account_total_transfers"), table_name="account")
    op.drop_index(op.f("ix_account_total_incomes"), table_name="account")
    op.drop_index(op.f("ix_account_total_expenses"), table_name="account")
    op.drop_index(op.f("ix_account_name"), table_name="account")
    op.drop_index(op.f("ix_account_initial_balance"), table_name="account")
    op.drop_index(op.f("ix_account_id"), table_name="account")
    op.drop_index(op.f("ix_account_current_balance"), table_name="account")
    op.drop_table("account")
    # ### end Alembic commands ###
