"""add balance to user account

Revision ID: 39b6ea580369
Revises: e3462a822029
Create Date: 2023-09-02 18:53:27.070390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39b6ea580369'
down_revision = 'e3462a822029'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('balance_total', sa.Float(), nullable=True))
    op.add_column('user', sa.Column('balance_income', sa.Float(), nullable=True))
    op.add_column('user', sa.Column('balance_outcome', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'balance_outcome')
    op.drop_column('user', 'balance_income')
    op.drop_column('user', 'balance_total')
    # ### end Alembic commands ###
