"""add type to accounts

Revision ID: 4410f9cfa10e
Revises: 797723a815e1
Create Date: 2025-03-21 15:59:38.170716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4410f9cfa10e'
down_revision = '797723a815e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Step 1: Create the enum type first
    account_type = sa.Enum('CHECKING', 'SAVINGS', 'CASH', 'STOCKS', 'CRYPTO', 'RETIREMENT',
                          'LOANS', 'CREDIT_CARDS', 'OVERDRAFTS', 'BUSINESS', 'FREELANCE',
                          'PREPAID', 'MISCELLANEOUS', name='accounttype')
    account_type.create(op.get_bind())

    # Step 2: Add the column as nullable first
    op.add_column('account', sa.Column('type', account_type, nullable=True))

    # Step 3: Update existing records to set MISCELLANEOUS as default
    op.execute("UPDATE account SET type = 'MISCELLANEOUS' WHERE type IS NULL")

    # Step 4: Make the column non-nullable
    op.alter_column('account', 'type', nullable=False)

    # Step 5: Create the index
    op.create_index(op.f('ix_account_type'), 'account', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_account_type'), table_name='account')
    op.drop_column('account', 'type')

    # Drop the enum type
    sa.Enum(name='accounttype').drop(op.get_bind())
    # ### end Alembic commands ###
