"""add income table

Revision ID: 447480971bb5
Revises: 8ba3134568e9
Create Date: 2023-09-02 05:52:53.776929

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "447480971bb5"
down_revision = "8ba3134568e9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "income",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("date", sa.Date(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.Column("account_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["account_id"],
            ["account.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_income_amount"), "income", ["amount"], unique=False)
    op.create_index(op.f("ix_income_date"), "income", ["date"], unique=False)
    op.create_index(
        op.f("ix_income_description"), "income", ["description"], unique=False
    )
    op.create_index(op.f("ix_income_id"), "income", ["id"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_income_id"), table_name="income")
    op.drop_index(op.f("ix_income_description"), table_name="income")
    op.drop_index(op.f("ix_income_date"), table_name="income")
    op.drop_index(op.f("ix_income_amount"), table_name="income")
    op.drop_table("income")
    # ### end Alembic commands ###
