"""add subcategory to expense and income

Revision ID: 5d8f1d524127
Revises: 14cb7994c598
Create Date: 2023-09-09 02:38:19.820211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5d8f1d524127'
down_revision = '14cb7994c598'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expense', sa.Column('subcategory_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'expense', 'subcategory', ['subcategory_id'], ['id'])
    op.add_column('income', sa.Column('subcategory_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'income', 'subcategory', ['subcategory_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'income', type_='foreignkey')
    op.drop_column('income', 'subcategory_id')
    op.drop_constraint(None, 'expense', type_='foreignkey')
    op.drop_column('expense', 'subcategory_id')
    # ### end Alembic commands ###
