"""add is_income to cateogry db

Revision ID: 60ad6f7febfb
Revises: ab765e1b5807
Create Date: 2024-08-14 19:57:22.186429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '60ad6f7febfb'
down_revision = 'ab765e1b5807'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('is_income', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_category_is_income'), 'category', ['is_income'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_category_is_income'), table_name='category')
    op.drop_column('category', 'is_income')
    # ### end Alembic commands ###
