"""add is_default to category and sub tables

Revision ID: 698be9656afe
Revises: 89973384bde3
Create Date: 2023-09-03 21:35:31.175710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '698be9656afe'
down_revision = '89973384bde3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('is_default', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_category_is_default'), 'category', ['is_default'], unique=False)
    op.add_column('subcategory', sa.Column('is_default', sa.Boolean(), nullable=False))
    op.create_index(op.f('ix_subcategory_is_default'), 'subcategory', ['is_default'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_subcategory_is_default'), table_name='subcategory')
    op.drop_column('subcategory', 'is_default')
    op.drop_index(op.f('ix_category_is_default'), table_name='category')
    op.drop_column('category', 'is_default')
    # ### end Alembic commands ###
