"""fix expense date type

Revision ID: 71779bc66bff
Revises: fa7a11b93453
Create Date: 2023-09-01 02:02:26.511190

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "71779bc66bff"
down_revision = "fa7a11b93453"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "expense",
        "date",
        existing_type=sa.VARCHAR(),
        type_=sa.Date(),
        existing_nullable=True,
        postgresql_using="date::date",
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "expense",
        "date",
        existing_type=sa.Date(),
        type_=sa.VARCHAR(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
