"""add transfer table

Revision ID: 761f9a4bf01f
Revises: 447480971bb5
Create Date: 2023-09-02 16:35:44.363376

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "761f9a4bf01f"
down_revision = "447480971bb5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("account", sa.Column("total_transfers_in", sa.Float(), nullable=True))
    op.add_column(
        "account", sa.Column("total_transfers_out", sa.Float(), nullable=True)
    )
    op.drop_index("ix_account_total_transfers", table_name="account")
    op.create_index(
        op.f("ix_account_total_transfers_in"),
        "account",
        ["total_transfers_in"],
        unique=False,
    )
    op.create_index(
        op.f("ix_account_total_transfers_out"),
        "account",
        ["total_transfers_out"],
        unique=False,
    )
    op.drop_column("account", "total_transfers")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "account",
        sa.Column(
            "total_transfers",
            postgresql.DOUBLE_PRECISION(precision=53),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.drop_index(op.f("ix_account_total_transfers_out"), table_name="account")
    op.drop_index(op.f("ix_account_total_transfers_in"), table_name="account")
    op.create_index(
        "ix_account_total_transfers", "account", ["total_transfers"], unique=False
    )
    op.drop_column("account", "total_transfers_out")
    op.drop_column("account", "total_transfers_in")
    # ### end Alembic commands ###
