"""add made_from to expenses and incomes

Revision ID: 797723a815e1
Revises: a2f6941377ef
Create Date: 2025-03-19 19:55:52.061997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '797723a815e1'
down_revision = 'a2f6941377ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expense', sa.Column('made_from', sa.String(), nullable=True))
    op.add_column('income', sa.Column('made_from', sa.String(), nullable=True))

    # Update existing records to have "Web" as the default value
    op.execute("UPDATE expense SET made_from = 'Web' WHERE made_from IS NULL")
    op.execute("UPDATE income SET made_from = 'Web' WHERE made_from IS NULL")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('income', 'made_from')
    op.drop_column('expense', 'made_from')
    # ### end Alembic commands ###
