"""add places to imports

Revision ID: 79a471c520ff
Revises: 1bf44fed8e19
Create Date: 2024-12-13 17:34:33.911726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79a471c520ff'
down_revision = '1bf44fed8e19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('import', sa.Column('sites_created', sa.Integer(), nullable=True))
    op.add_column('place', sa.Column('import_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'place', 'import', ['import_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'place', type_='foreignkey')
    op.drop_column('place', 'import_id')
    op.drop_column('import', 'sites_created')
    # ### end Alembic commands ###
