"""add feedback table

Revision ID: 7b37b77a916d
Revises: 469548e06c7f
Create Date: 2025-07-24 21:51:43.039554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b37b77a916d'
down_revision = '469548e06c7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
