"""rename title for name on place table

Revision ID: 8844eb40d730
Revises: cd0c048002f2
Create Date: 2023-09-05 02:48:15.129427

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8844eb40d730"
down_revision = "cd0c048002f2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("place", sa.Column("name", sa.String(), nullable=True))
    op.drop_index("ix_place_title", table_name="place")
    op.create_index(op.f("ix_place_name"), "place", ["name"], unique=False)
    op.drop_column("place", "title")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "place", sa.Column("title", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.drop_index(op.f("ix_place_name"), table_name="place")
    op.create_index("ix_place_title", "place", ["title"], unique=False)
    op.drop_column("place", "name")
    # ### end Alembic commands ###
