"""fix wrong mapped account expenses

Revision ID: 8ba3134568e9
Revises: 0e747f730710
Create Date: 2023-09-01 17:34:05.878444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ba3134568e9'
down_revision = '0e747f730710'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
