"""Add column uuid to User model

Revision ID: a83c8e89f9eb
Revises: 5d8f1d524127
Create Date: 2024-07-26 22:16:39.395792

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a83c8e89f9eb"
down_revision = "5d8f1d524127"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("uuid", sa.String(), nullable=False))
    op.alter_column("user", "email", existing_type=sa.VARCHAR(), nullable=True)
    op.create_index(op.f("ix_user_uuid"), "user", ["uuid"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_uuid"), table_name="user")
    op.alter_column("user", "email", existing_type=sa.VARCHAR(), nullable=False)
    op.drop_column("user", "uuid")
    # ### end Alembic commands ###
