"""add feedback table again lol

Revision ID: a8a96707857e
Revises: 7b37b77a916d
Create Date: 2025-07-24 21:53:43.921042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8a96707857e'
down_revision = '7b37b77a916d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
