"""make name and hashed_password nullable

Revision ID: ab765e1b5807
Revises: b573d45c6a99
Create Date: 2024-07-31 22:39:15.655978

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ab765e1b5807"
down_revision = "b573d45c6a99"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "name", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "user", "hashed_password", existing_type=sa.VARCHAR(), nullable=True
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "user", "hashed_password", existing_type=sa.VARCHAR(), nullable=False
    )
    op.alter_column("user", "name", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
