"""fix account model

Revision ID: abaaf5a51f93
Revises: 37e5650bd60b
Create Date: 2023-09-01 17:22:21.213870

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abaaf5a51f93'
down_revision = '37e5650bd60b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('owner_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'account', 'user', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'account', type_='foreignkey')
    op.drop_column('account', 'owner_id')
    # ### end Alembic commands ###
