"""fix transfer relationships

Revision ID: acdfd62f770e
Revises: e9ed0db12277
Create Date: 2023-09-02 16:54:53.081032

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acdfd62f770e'
down_revision = 'e9ed0db12277'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
