"""add_investiment_tables

Revision ID: ad6c96956dc4
Revises: 1b088076d25c
Create Date: 2026-01-09 20:28:42.120421

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ad6c96956dc4"
down_revision = "1b088076d25c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "asset",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("symbol", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column(
            "asset_class",
            sa.Enum("EQUITIES", "FIXED_INCOME", "CRYPTO", "FUNDS", name="assetclass"),
            nullable=False,
        ),
        sa.Column(
            "asset_type",
            sa.Enum(
                "STOCK",
                "ETF",
                "BOND",
                "CETES",
                "TREASURY",
                "CRYPTOCURRENCY",
                "MUTUAL_FUND",
                "INDEX_FUND",
                name="assettype",
            ),
            nullable=False,
        ),
        sa.Column("currency", sa.Enum("MXN", "USD", name="currency"), nullable=False),
        sa.Column(
            "market",
            sa.Enum("BMV", "NYSE", "NASDAQ", "CRYPTO", "OTC", name="market"),
            nullable=False,
        ),
        sa.Column("sector", sa.String(), nullable=True),
        sa.Column("country", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_asset_asset_class"), "asset", ["asset_class"], unique=False
    )
    op.create_index(op.f("ix_asset_asset_type"), "asset", ["asset_type"], unique=False)
    op.create_index(op.f("ix_asset_currency"), "asset", ["currency"], unique=False)
    op.create_index(op.f("ix_asset_id"), "asset", ["id"], unique=True)
    op.create_index(op.f("ix_asset_market"), "asset", ["market"], unique=False)
    op.create_index(op.f("ix_asset_name"), "asset", ["name"], unique=False)
    op.create_index(op.f("ix_asset_symbol"), "asset", ["symbol"], unique=True)
    op.create_table(
        "assetprice",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("asset_id", sa.Integer(), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.Column("currency", sa.Enum("MXN", "USD", name="currency"), nullable=False),
        sa.Column("price_usd", sa.Float(), nullable=False),
        sa.Column("price_mxn", sa.Float(), nullable=False),
        sa.Column("open_price", sa.Float(), nullable=True),
        sa.Column("high_price", sa.Float(), nullable=True),
        sa.Column("low_price", sa.Float(), nullable=True),
        sa.Column("previous_close", sa.Float(), nullable=True),
        sa.Column("volume", sa.Float(), nullable=True),
        sa.Column("change", sa.Float(), nullable=True),
        sa.Column("change_percent", sa.Float(), nullable=True),
        sa.Column(
            "fetched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["asset.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_assetprice_asset_id"), "assetprice", ["asset_id"], unique=False
    )
    op.create_index(op.f("ix_assetprice_id"), "assetprice", ["id"], unique=True)
    op.create_table(
        "holding",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("asset_id", sa.Integer(), nullable=False),
        sa.Column("quantity", sa.Float(), nullable=False),
        sa.Column("avg_cost_basis", sa.Float(), nullable=False),
        sa.Column(
            "cost_currency", sa.Enum("MXN", "USD", name="currency"), nullable=False
        ),
        sa.Column("total_invested", sa.Float(), nullable=False),
        sa.Column("current_value", sa.Float(), nullable=False),
        sa.Column("current_value_mxn", sa.Float(), nullable=False),
        sa.Column("current_value_usd", sa.Float(), nullable=False),
        sa.Column("unrealized_gain_loss", sa.Float(), nullable=False),
        sa.Column("unrealized_gain_loss_pct", sa.Float(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["asset.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_holding_asset_id"), "holding", ["asset_id"], unique=False)
    op.create_index(op.f("ix_holding_id"), "holding", ["id"], unique=True)
    op.create_index(op.f("ix_holding_owner_id"), "holding", ["owner_id"], unique=False)
    op.create_table(
        "investmenttransaction",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("owner_id", sa.Integer(), nullable=False),
        sa.Column("holding_id", sa.Integer(), nullable=False),
        sa.Column(
            "transaction_type",
            sa.Enum(
                "BUY",
                "SELL",
                "DIVIDEND",
                "SPLIT",
                "TRANSFER_IN",
                "TRANSFER_OUT",
                name="transactiontype",
            ),
            nullable=False,
        ),
        sa.Column("quantity", sa.Float(), nullable=False),
        sa.Column("price_per_unit", sa.Float(), nullable=False),
        sa.Column("currency", sa.Enum("MXN", "USD", name="currency"), nullable=False),
        sa.Column("total_amount", sa.Float(), nullable=False),
        sa.Column("fees", sa.Float(), nullable=False),
        sa.Column("exchange_rate_to_usd", sa.Float(), nullable=True),
        sa.Column("exchange_rate_to_mxn", sa.Float(), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("broker", sa.String(), nullable=True),
        sa.Column("executed_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["holding_id"],
            ["holding.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_investmenttransaction_holding_id"),
        "investmenttransaction",
        ["holding_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_investmenttransaction_id"),
        "investmenttransaction",
        ["id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_investmenttransaction_owner_id"),
        "investmenttransaction",
        ["owner_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_investmenttransaction_transaction_type"),
        "investmenttransaction",
        ["transaction_type"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_investmenttransaction_transaction_type"),
        table_name="investmenttransaction",
    )
    op.drop_index(
        op.f("ix_investmenttransaction_owner_id"), table_name="investmenttransaction"
    )
    op.drop_index(
        op.f("ix_investmenttransaction_id"), table_name="investmenttransaction"
    )
    op.drop_index(
        op.f("ix_investmenttransaction_holding_id"), table_name="investmenttransaction"
    )
    op.drop_table("investmenttransaction")
    op.drop_index(op.f("ix_holding_owner_id"), table_name="holding")
    op.drop_index(op.f("ix_holding_id"), table_name="holding")
    op.drop_index(op.f("ix_holding_asset_id"), table_name="holding")
    op.drop_table("holding")
    op.drop_index(op.f("ix_assetprice_id"), table_name="assetprice")
    op.drop_index(op.f("ix_assetprice_asset_id"), table_name="assetprice")
    op.drop_table("assetprice")
    op.drop_index(op.f("ix_asset_symbol"), table_name="asset")
    op.drop_index(op.f("ix_asset_name"), table_name="asset")
    op.drop_index(op.f("ix_asset_market"), table_name="asset")
    op.drop_index(op.f("ix_asset_id"), table_name="asset")
    op.drop_index(op.f("ix_asset_currency"), table_name="asset")
    op.drop_index(op.f("ix_asset_asset_type"), table_name="asset")
    op.drop_index(op.f("ix_asset_asset_class"), table_name="asset")
    op.drop_table("asset")
    # ### end Alembic commands ###
