"""add goal_id back to income table

Revision ID: add_goal_id_back_to_income_table
Revises: 26509aaa0bab
Create Date: 2025-09-06 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_goal_id_back_to_income_table'
down_revision = '26509aaa0bab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('income', sa.Column('goal_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'income', 'goal', ['goal_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'income', type_='foreignkey')
    op.drop_column('income', 'goal_id')
    # ### end Alembic commands ###