"""add account link to investments

Revision ID: af1c276ebdd1
Revises: c9b2e5f8a1d1
Create Date: 2026-05-02 23:12:38.836277

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'af1c276ebdd1'
down_revision = 'c9b2e5f8a1d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('total_investments', sa.Float(), nullable=True))
    op.add_column('account', sa.Column('logo', sa.String(), nullable=True))
    op.create_index(op.f('ix_account_total_investments'), 'account', ['total_investments'], unique=False)
    op.add_column('holding', sa.Column('account_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_holding_account_id'), 'holding', ['account_id'], unique=False)
    op.create_foreign_key(None, 'holding', 'account', ['account_id'], ['id'])
    op.add_column('investmenttransaction', sa.Column('account_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_investmenttransaction_account_id'), 'investmenttransaction', ['account_id'], unique=False)
    op.create_foreign_key(None, 'investmenttransaction', 'account', ['account_id'], ['id'])
    op.drop_column('investmenttransaction', 'broker')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('investmenttransaction', sa.Column('broker', postgresql.ENUM('FIDELITY', 'SCHWAB', 'VANGUARD', 'ETRADE', 'TD_AMERITRADE', 'MERRILL', 'MORGAN_STANLEY', 'JP_MORGAN', 'ROBINHOOD', 'WEBULL', 'SOFI', 'M1_FINANCE', 'ALLY', 'TRADESTATION', 'FIRSTRADE', 'PUBLIC', 'TASTYTRADE', 'GBM', 'KUSPIT', 'ACTINVER', 'BURSANET', 'BBVA_TRADER', 'FINAMEX', 'BANORTE', 'VECTOR', 'INTERCAM', 'MONEX', 'COINBASE', 'BINANCE', 'KRAKEN', 'GEMINI', 'CRYPTO_COM', 'BITSO', 'KUCOIN', 'BITSTAMP', 'OKX', 'BYBIT', 'IBKR', 'DEGIRO', 'ETORO', 'TRADING_212', 'SAXO', 'SWISSQUOTE', 'CMC', 'IG', name='broker'), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'investmenttransaction', type_='foreignkey')
    op.drop_index(op.f('ix_investmenttransaction_account_id'), table_name='investmenttransaction')
    op.drop_column('investmenttransaction', 'account_id')
    op.drop_constraint(None, 'holding', type_='foreignkey')
    op.drop_index(op.f('ix_holding_account_id'), table_name='holding')
    op.drop_column('holding', 'account_id')
    op.drop_index(op.f('ix_account_total_investments'), table_name='account')
    op.drop_column('account', 'logo')
    op.drop_column('account', 'total_investments')
    # ### end Alembic commands ###
