"""fix category relationship

Revision ID: af5122ef300d
Revises: 210562bb3adc
Create Date: 2023-09-03 01:57:07.859696

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "af5122ef300d"
down_revision = "210562bb3adc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
