"""recreate_tables

Revision ID: b1c8d0efb6f3
Revises: 1bf44fed8e19
Create Date: 2024-10-23 22:51:24.640611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1c8d0efb6f3'
down_revision = '1bf44fed8e19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('service', sa.Enum('CSV', 'BLUECOINS', name='importservice', create_constraint=True), nullable=False),
    sa.Column('file_content', sa.String(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('total_transactions_imported', sa.Integer(), nullable=True),
    sa.Column('expenses_imported', sa.Integer(), nullable=True),
    sa.Column('incomes_imported', sa.Integer(), nullable=True),
    sa.Column('accounts_created', sa.Integer(), nullable=True),
    sa.Column('unmatched_categories', sa.Integer(), nullable=True),
    sa.Column('total_rows_processed', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_id'), 'import', ['id'], unique=True)
    op.create_foreign_key(None, 'account', 'import', ['import_id'], ['id'])
    op.create_foreign_key(None, 'expense', 'import', ['import_id'], ['id'])
    op.create_foreign_key(None, 'income', 'import', ['import_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'income', type_='foreignkey')
    op.drop_constraint(None, 'expense', type_='foreignkey')
    op.drop_constraint(None, 'account', type_='foreignkey')
    op.drop_index(op.f('ix_import_id'), table_name='import')
    op.drop_table('import')
    # ### end Alembic commands ###
