"""add goal model

Revision ID: b404e628479
Revises: f49f6f53a283
Create Date: 2025-09-05 21:39:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b404e628479'
down_revision = 'f49f6f53a283'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('goal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('target_amount', sa.Float(), nullable=False),
    sa.Column('current_amount', sa.Float(), nullable=True),
    sa.Column('category', sa.Enum('EMERGENCY_FUND', 'VACATION', 'CAR', 'HOUSE', 'EDUCATION', 'INVESTMENT', 'DEBT_PAYOFF', 'WEDDING', 'RETIREMENT', 'OTHER', name='goalcategory'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'COMPLETED', 'PAUSED', 'CANCELLED', name='goalstatus'), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_goal_category'), 'goal', ['category'], unique=False)
    op.create_index(op.f('ix_goal_current_amount'), 'goal', ['current_amount'], unique=False)
    op.create_index(op.f('ix_goal_id'), 'goal', ['id'], unique=True)
    op.create_index(op.f('ix_goal_name'), 'goal', ['name'], unique=False)
    op.create_index(op.f('ix_goal_status'), 'goal', ['status'], unique=False)
    op.create_index(op.f('ix_goal_target_amount'), 'goal', ['target_amount'], unique=False)
    op.create_index(op.f('ix_goal_target_date'), 'goal', ['target_date'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_goal_target_date'), table_name='goal')
    op.drop_index(op.f('ix_goal_target_amount'), table_name='goal')
    op.drop_index(op.f('ix_goal_status'), table_name='goal')
    op.drop_index(op.f('ix_goal_name'), table_name='goal')
    op.drop_index(op.f('ix_goal_id'), table_name='goal')
    op.drop_index(op.f('ix_goal_current_amount'), table_name='goal')
    op.drop_index(op.f('ix_goal_category'), table_name='goal')
    op.drop_table('goal')
    op.execute('DROP TYPE goalcategory')
    op.execute('DROP TYPE goalstatus')
    # ### end Alembic commands ###