"""fix uuid auth

Revision ID: b573d45c6a99
Revises: a83c8e89f9eb
Create Date: 2024-07-31 22:29:39.032379

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b573d45c6a99"
down_revision = "a83c8e89f9eb"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "uuid", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("user", "uuid", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
