"""add expense model

Revision ID: cc8061d8a16a
Revises: 0430ce195cdb
Create Date: 2023-08-31 01:58:49.446587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc8061d8a16a'
down_revision = '0430ce195cdb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('expense',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('date', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_expense_amount'), 'expense', ['amount'], unique=False)
    op.create_index(op.f('ix_expense_date'), 'expense', ['date'], unique=False)
    op.create_index(op.f('ix_expense_description'), 'expense', ['description'], unique=False)
    op.create_index(op.f('ix_expense_id'), 'expense', ['id'], unique=True)
    op.create_index(op.f('ix_expense_title'), 'expense', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_expense_title'), table_name='expense')
    op.drop_index(op.f('ix_expense_id'), table_name='expense')
    op.drop_index(op.f('ix_expense_description'), table_name='expense')
    op.drop_index(op.f('ix_expense_date'), table_name='expense')
    op.drop_index(op.f('ix_expense_amount'), table_name='expense')
    op.drop_table('expense')
    # ### end Alembic commands ###
