"""remove place_id from transfer

Revision ID: cd0c048002f2
Revises: db9f0720dfa6
Create Date: 2023-09-05 02:41:31.401194

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "cd0c048002f2"
down_revision = "db9f0720dfa6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("transfer_place_id_fkey", "transfer", type_="foreignkey")
    op.drop_column("transfer", "place_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "transfer",
        sa.Column("place_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.create_foreign_key(
        "transfer_place_id_fkey", "transfer", "place", ["place_id"], ["id"]
    )
    # ### end Alembic commands ###
