"""Add import_id to expense, income, and account models

Revision ID: d07dbf6d50de
Revises: d4b9d02d4abb
Create Date: 2024-10-23 22:01:31.697903

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd07dbf6d50de'
down_revision = 'd4b9d02d4abb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('import',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('service', sa.Enum('CSV', 'BLUECOINS', name='importservice'), nullable=False),
    sa.Column('file_content', sa.String(), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('total_transactions_imported', sa.Integer(), nullable=True),
    sa.Column('expenses_imported', sa.Integer(), nullable=True),
    sa.Column('incomes_imported', sa.Integer(), nullable=True),
    sa.Column('accounts_created', sa.Integer(), nullable=True),
    sa.Column('unmatched_categories', sa.Integer(), nullable=True),
    sa.Column('total_rows_processed', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_date'), 'import', ['date'], unique=False)
    op.create_index(op.f('ix_import_id'), 'import', ['id'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_import_id'), table_name='import')
    op.drop_index(op.f('ix_import_date'), table_name='import')
    op.drop_table('import')
    # ### end Alembic commands ###
