"""Add created_at and updated_at to all models

Revision ID: d3a45bc07f9a
Revises: 0be6c139413c
Create Date: 2024-09-11 03:33:52.627999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3a45bc07f9a'
down_revision = '0be6c139413c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('account', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('account', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('category', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('category', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('expense', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('expense', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('income', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('income', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('place', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('place', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('subcategory', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('subcategory', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('transfer', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('transfer', sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True))

    op.execute("UPDATE account SET created_at = NOW() WHERE created_at IS NULL")
    op.execute("UPDATE category SET created_at = NOW() WHERE created_at IS NULL")
    op.execute("UPDATE subcategory SET created_at = NOW() WHERE created_at IS NULL")
    op.execute("UPDATE expense SET created_at = NOW() WHERE created_at IS NULL")
    op.execute("UPDATE income SET created_at = NOW() WHERE created_at IS NULL")
    op.execute("UPDATE transfer SET created_at = NOW() WHERE created_at IS NULL")
    op.execute("UPDATE place SET created_at = NOW() WHERE created_at IS NULL")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transfer', 'updated_at')
    op.drop_column('transfer', 'created_at')
    op.drop_column('subcategory', 'updated_at')
    op.drop_column('subcategory', 'created_at')
    op.drop_column('place', 'updated_at')
    op.drop_column('place', 'created_at')
    op.drop_column('income', 'updated_at')
    op.drop_column('income', 'created_at')
    op.drop_column('expense', 'updated_at')
    op.drop_column('expense', 'created_at')
    op.drop_column('category', 'updated_at')
    op.drop_column('category', 'created_at')
    op.drop_column('account', 'updated_at')
    op.drop_column('account', 'created_at')
    # ### end Alembic commands ###
