"""remove color from subcategory

Revision ID: d497016f66f8
Revises: 698be9656afe
Create Date: 2023-09-03 22:23:45.426057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd497016f66f8'
down_revision = '698be9656afe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_subcategory_color', table_name='subcategory')
    op.drop_column('subcategory', 'color')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subcategory', sa.Column('color', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index('ix_subcategory_color', 'subcategory', ['color'], unique=False)
    # ### end Alembic commands ###
