"""add place table

Revision ID: db9f0720dfa6
Revises: d497016f66f8
Create Date: 2023-09-05 02:32:37.126791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db9f0720dfa6'
down_revision = 'd497016f66f8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('place',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('is_online', sa.Boolean(), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_place_id'), 'place', ['id'], unique=True)
    op.create_index(op.f('ix_place_is_online'), 'place', ['is_online'], unique=False)
    op.create_index(op.f('ix_place_title'), 'place', ['title'], unique=False)
    op.add_column('expense', sa.Column('place_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'expense', 'place', ['place_id'], ['id'])
    op.add_column('income', sa.Column('place_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'income', 'place', ['place_id'], ['id'])
    op.add_column('transfer', sa.Column('place_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transfer', 'place', ['place_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transfer', type_='foreignkey')
    op.drop_column('transfer', 'place_id')
    op.drop_constraint(None, 'income', type_='foreignkey')
    op.drop_column('income', 'place_id')
    op.drop_constraint(None, 'expense', type_='foreignkey')
    op.drop_column('expense', 'place_id')
    op.drop_index(op.f('ix_place_title'), table_name='place')
    op.drop_index(op.f('ix_place_is_online'), table_name='place')
    op.drop_index(op.f('ix_place_id'), table_name='place')
    op.drop_table('place')
    # ### end Alembic commands ###
