"""add transfer table again lol

Revision ID: e9ed0db12277
Revises: 761f9a4bf01f
Create Date: 2023-09-02 16:51:52.590209

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "e9ed0db12277"
down_revision = "761f9a4bf01f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "transfer",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("amount", sa.Float(), nullable=False),
        sa.Column("date", sa.Date(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("from_acc", sa.Integer(), nullable=True),
        sa.Column("to_acc", sa.Integer(), nullable=True),
        sa.Column("owner_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["from_acc"],
            ["account.id"],
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["user.id"],
        ),
        sa.ForeignKeyConstraint(
            ["to_acc"],
            ["account.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_transfer_amount"), "transfer", ["amount"], unique=False)
    op.create_index(op.f("ix_transfer_date"), "transfer", ["date"], unique=False)
    op.create_index(
        op.f("ix_transfer_description"), "transfer", ["description"], unique=False
    )
    op.create_index(op.f("ix_transfer_id"), "transfer", ["id"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_transfer_id"), table_name="transfer")
    op.drop_index(op.f("ix_transfer_description"), table_name="transfer")
    op.drop_index(op.f("ix_transfer_date"), table_name="transfer")
    op.drop_index(op.f("ix_transfer_amount"), table_name="transfer")
    op.drop_table("transfer")
    # ### end Alembic commands ###
