"""Add import_id to expense, income, and account models

Revision ID: edbcf36d408a
Revises: d07dbf6d50de
Create Date: 2024-10-23 22:05:42.293673

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "edbcf36d408a"
down_revision = "d07dbf6d50de"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("account", sa.Column("import_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "account", "import", ["import_id"], ["id"])
    op.add_column("expense", sa.Column("import_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "expense", "import", ["import_id"], ["id"])
    op.add_column("income", sa.Column("import_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "income", "import", ["import_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "income", type_="foreignkey")
    op.drop_column("income", "import_id")
    op.drop_constraint(None, "expense", type_="foreignkey")
    op.drop_column("expense", "import_id")
    op.drop_constraint(None, "account", type_="foreignkey")
    op.drop_column("account", "import_id")
    # ### end Alembic commands ###
