"""remove goal_id from expense table

Revision ID: remove_goal_id_from_expense_table
Revises: add_goal_id_back_to_income_table
Create Date: 2025-09-06 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'remove_goal_id_from_expense_table'
down_revision = 'add_goal_id_back_to_income_table'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'expense', type_='foreignkey')
    op.drop_column('expense', 'goal_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expense', sa.Column('goal_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'expense', 'goal', ['goal_id'], ['id'])
    # ### end Alembic commands ###