"""add goal_id to transactions

Revision ID: w8c5h14uldi0
Revises: oz0191glw8ir
Create Date: 2025-09-06 02:55:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'w8c5h14uldi0'
down_revision = 'oz0191glw8ir'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expense', sa.Column('goal_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'expense', 'goal', ['goal_id'], ['id'])
    
    op.add_column('income', sa.Column('goal_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'income', 'goal', ['goal_id'], ['id'])
    
    op.add_column('transfer', sa.Column('goal_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'transfer', 'goal', ['goal_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transfer', type_='foreignkey')
    op.drop_column('transfer', 'goal_id')
    
    op.drop_constraint(None, 'income', type_='foreignkey')
    op.drop_column('income', 'goal_id')
    
    op.drop_constraint(None, 'expense', type_='foreignkey')
    op.drop_column('expense', 'goal_id')
    # ### end Alembic commands ###